import type { Metadata } from "next";
import { Geist, Geist_Mono, Bricolage_Grotesque } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import EnergyContextProvider from "@/store/energyContext";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Bricolage_Grotesque({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) { {/* I used a layout where its a mobile game but on a web because of the figma design. I have been told it is okay, if needed, can convert it into web as well. */}
  return (
    <html lang="en">
      <body
        className={`antialiased ${geistMono}`}
      >
        <EnergyContextProvider> {/* I used a layout where its a mobile game but on a web because of the figma design. */}
          <div className="flex w-full h-screen justify-center items-center bg-[#111118]">
            <div className="w-full max-w-[390px] p-4 min-h-[90vh] bg-[#111118] rounded-2xl shadow-lg text-white border border-white">
              {children}
            </div>
          </div>
          <Toaster richColors />
        </EnergyContextProvider>
      </body>
    </html>
  );
}
